name: the_cats
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.1
  http: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_image.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true
  assets:
    - .env
    - "assets/icons/icon.png"
    - "assets/images/splash_image.png"
